# Generated by Django 2.0.2 on 2018-02-21 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mun', '0002_auto_20180221_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mun',
            name='text',
        ),
        migrations.RemoveField(
            model_name='mun',
            name='title',
        ),
        migrations.AddField(
            model_name='mun',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mun',
            name='empID',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mun',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mun',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
